### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by PetrusVermaak** [hifihedgehog/change-password-cyberpanel#1]
Hi there,

Installed the plugin, activated and configured on my CyberPanel Rainloop, but cannot change passwords.

**Comment by hifihedgehog** [comment]
Noted. I see CyberPanel no longer stores the user credentials in a visible CyberPanel database. Investigating.

**Comment by hifihedgehog** [comment]
Pinging @usmannasir. Where is the new location for email users? I noticed the Cyberpanel table is no longer visible in phpMyAdmin. Thanks!

**Comment by hifihedgehog** [comment]
> Hi there,
> 
> Installed the plugin, activated and configured on my CyberPanel Rainloop, but cannot change passwords.

It turns out the CyberPanel database is still present, but it appears to be only hidden in phpMyAdmin. To use the plugin, you must be using your CyberPanel root database credentials for password changing to work correctly. Can you verify you added your CyberPanel root credentials in this location? It would be under your Rainloop administrator plugins section, or https://[YOUR RAINLOOP DOMAIN]/?admin#/plugins. It must be entered like so:

![image](https://user-images.githubusercontent.com/16614343/95210277-55842580-07b9-11eb-9f1c-d0dce6764046.png)

**Comment by PetrusVermaak** [comment]
Hi there

Yes can confirm I added the MyPHPAdmin root password. Logged a ticket with CyberPanel support and they also checked... but no go...

**Comment by aonsyed** [comment]
> > Hi there,
> > Installed the plugin, activated and configured on my CyberPanel Rainloop, but cannot change passwords.
> 
> It turns out the CyberPanel database is still present, but it appears to be only hidden in phpMyAdmin. To use the plugin, you must be using your CyberPanel root database credentials for password changing to work correctly. Can you verify you added your CyberPanel root credentials in this location? It would be under your Rainloop administrator plugins section, or https://[YOUR RAINLOOP DOMAIN]/?admin#/plugins. It must be entered like so:
> 
> ![image](https://user-images.githubusercontent.com/16614343/95210277-55842580-07b9-11eb-9f1c-d0dce6764046.png)

Hello This is Muttahir from CyberPanel, there have been no changes to cyberpanel database visibility lately, can you tell me how to reproduce this ?

**Comment by hifihedgehog** [comment]
> > > Hi there,
> > > Installed the plugin, activated and configured on my CyberPanel Rainloop, but cannot change passwords.
> > 
> > 
> > It turns out the CyberPanel database is still present, but it appears to be only hidden in phpMyAdmin. To use the plugin, you must be using your CyberPanel root database credentials for password changing to work correctly. Can you verify you added your CyberPanel root credentials in this location? It would be under your Rainloop administrator plugins section, or https://[YOUR RAINLOOP DOMAIN]/?admin#/plugins. It must be entered like so:
> > ![image](https://user-images.githubusercontent.com/16614343/95210277-55842580-07b9-11eb-9f1c-d0dce6764046.png)
> 
> Hello This is Muttahir from CyberPanel, there have been no changes to cyberpanel database visibility lately, can you tell me how to reproduce this ?

I wish I could, but I am not sure how to reproduce it. All I know is some databases, like CyberPanel and Mailscanner, are not visible in my PhpMyAdmin, while my website ones are. I do have a ticket out in the CyberPanel platform support center. You can feel free to browse around in my VPS with the credentials I provided under the ticket.

**Comment by PetrusVermaak** [comment]
So there is no way to make this work? You're my last hope, there is nothing else that can do this....

**Comment by hifihedgehog** [comment]
I already verifed that any issue is non-existent with the plugin. Either your configurations are incorrect or your system itself is having troubles well beyond the scope of this plugin.
